/* manifest.h — Text file manifest (auto-generated by gen_manifest.py) */
#ifndef MANIFEST_H
#define MANIFEST_H

#include "libc_min.h"

typedef struct {
    const char *name;       /* Filename */
    uint32_t    offset;     /* Byte offset into text_blob */
    uint32_t    size;       /* Size in bytes */
} text_entry_t;

extern const text_entry_t text_manifest[];
extern const int text_count;

/* Symbol from linker script: start of text blob in memory */
extern char __text_blob_start[];

#endif /* MANIFEST_H */
