#!/usr/bin/env python3
"""gen_manifest.py — Scans texts/ for .txt files, generates manifest.c and text_blob.bin.

Usage: python3 tools/gen_manifest.py <texts_dir> <output_manifest_c> <output_blob_bin>

Example: python3 tools/gen_manifest.py texts/ build/manifest.c build/text_blob.bin
"""

import os
import sys

def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} <texts_dir> <output_manifest.c> <output_blob.bin>")
        sys.exit(1)

    texts_dir = sys.argv[1]
    manifest_c = sys.argv[2]
    blob_bin = sys.argv[3]

    # Find all .txt files, sorted alphabetically
    files = sorted([
        f for f in os.listdir(texts_dir)
        if f.endswith('.txt') and os.path.isfile(os.path.join(texts_dir, f))
    ])

    if not files:
        print(f"WARNING: No .txt files found in {texts_dir}")

    # Build manifest entries and concatenate blob
    entries = []
    blob_data = bytearray()
    offset = 0

    for fname in files:
        fpath = os.path.join(texts_dir, fname)
        with open(fpath, 'rb') as f:
            data = f.read()
        size = len(data)
        entries.append((fname, offset, size))
        blob_data.extend(data)
        offset += size
        print(f"  {fname}: {size} bytes at offset {offset - size}")

    # Write blob
    os.makedirs(os.path.dirname(blob_bin) or '.', exist_ok=True)
    with open(blob_bin, 'wb') as f:
        f.write(blob_data)
    print(f"Blob: {len(blob_data)} bytes total -> {blob_bin}")

    # Generate manifest.c
    os.makedirs(os.path.dirname(manifest_c) or '.', exist_ok=True)
    with open(manifest_c, 'w') as f:
        f.write("/* AUTO-GENERATED by gen_manifest.py — do not edit */\n")
        f.write('#include "manifest.h"\n\n')
        f.write("const text_entry_t text_manifest[] = {\n")
        for name, off, sz in entries:
            f.write(f'    {{ "{name}", {off}, {sz} }},\n')
        f.write("};\n\n")
        f.write(f"const int text_count = {len(entries)};\n")
    print(f"Manifest: {len(entries)} entries -> {manifest_c}")

if __name__ == "__main__":
    main()
